services:
    _defaults:
        autowire: true

    Netgen\Bundle\EnhancedBinaryFileBundle\Core\FieldType\EnhancedBinaryFile\Type:
        arguments:
            - '@Ibexa\Core\IO\MimeTypeDetector\FileInfo'
            - '@Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface'
            - [ '@Ibexa\Core\FieldType\Validator\FileExtensionBlackListValidator' ]
            - '@?Ibexa\Core\MVC\Symfony\FieldType\BinaryBase\ContentDownloadUrlGenerator'
        tags:
            - { name: ibexa.field_type, alias: enhancedezbinaryfile }

    ezpublish.fieldType.enhancedezbinaryfile.storage_gateway:
        class: Ibexa\Core\FieldType\BinaryFile\BinaryFileStorage\Gateway\DoctrineStorage
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler.gateway, alias: enhancedezbinaryfile, identifier: LegacyStorage }

    ezpublish.enhancedezbinaryfile.external_storage_handler:
        class: Ibexa\Core\FieldType\BinaryBase\BinaryBaseStorage
        arguments:
            - "@ezpublish.fieldType.ezbinaryfile.storage_gateway"
            - "@ezpublish.fieldType.ezbinaryfile.io_service"
            - "@ezpublish.fieldType.ezbinaryfile.pathGenerator"
            - "@ezpublish.core.io.mimeTypeDetector"
        tags:
            - { name: ezpublish.fieldType.externalStorageHandler, alias: enhancedezbinaryfile }
