services:
    Netgen\Bundle\EnhancedBinaryFileBundle\FieldHandler\EnhancedBinaryFileHandler:
        autowire: true
        arguments:
            $ioService: '@Ibexa\Core\FieldType\Image\IO\Legacy'
        tags:
            - { name: netgen_information_collection.field_handler.custom }
