netgen_enhancedezbinaryfile.route.download_binary_file:
    path: /netgen/enhancedezbinaryfile/download/{infocollectionAttributeId}
    defaults: { _controller: Netgen\Bundle\EnhancedBinaryFileBundle\Controller\DownloadController:downloadCollectedEnhancedEzBinaryFileAction }
    methods: [GET]

