services:
    Netgen\Bundle\EnhancedBinaryFileBundle\Controller\DownloadController:
        autowire: true
        autoconfigure: true
        tags:
            - "controller.service_arguments"
        arguments:
            - "@netgen_information_collection.repository.ez_info_collection_attribute"
            - "@netgen_information_collection.repository.ez_info_collection"
            - "@ibexa.core.io.service"
            - "@ibexa.api.repository"

