services:
    Netgen\Bundle\EnhancedBinaryFileBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\Converter:
        tags:
            - { name: ibexa.field_type.storage.legacy.converter, alias: enhancedezbinaryfile }

    ezpublish.fieldType.indexable.enhancedezbinaryfile:
        class: Ibexa\Core\FieldType\Unindexed
        tags:
            - { name: ibexa.field_type.indexable, alias: enhancedezbinaryfile }

